services:
  backend:
    build: ./backend
    volumes:
      - workoutdata:/app/data
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
volumes:
  workoutdata:
