services:
  backend:
    build: ./backend
    volumes:
      - workoutdata:/app/data
    ports:
      - "8225:8000"  # Accessible from all interfaces
    environment:
      - PYTHONPATH=/app
      
  frontend:
    build: ./frontend
    ports:
      - "3122:3000"  # Accessible from all interfaces
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  workoutdata: