services:
  backend:
    build: ./backend
    volumes:
      - workoutdata:/app/data
    ports:
      - "8222:8000"
  frontend:
    build: ./frontend
    ports:
      - "3122:3000"
    environment:
      - VITE_API_URL=http://localhost:8222
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
volumes:
  workoutdata:
